name: Deploy to Live Instance

on:
  push:
    tags:
      - release-production-*
  # Optionally configure to run only for specific files. For example:
  # paths:
  # - "website/**"

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - run: npm run lint && npm run build 
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}" --only hosting --non-interactive
        env: 
          FIREBASE_TOKEN: "${{ secrets.FIREBASE_TOKEN }}"